## Nodal Analysis

In [81]:
import numpy as np
import matplotlib.pyplot as plt

One of the fundamental laws used in circuit analysis is Kirchhoff's Current Law (KCL). This law is summarized as the total current entering the junction must be equal to the total current leaving a junction. Since current is the flow of charge (specifically, $I = \frac{dQ}{dt}$), this law is a statement of conservation of charge. 

We can combine KCL with Ohm's law ($V=IR$) to easily find the voltage at junctions in complex circuits where you can't (or don't want to) manually analyze the system by hand. 

I'll demonstrate this concept on the simple circuit below (the units on the resistors are in Ohms).

<img src="Sample.png">

This circuit is really simple, and you can solve for the values of $V_1$ and $V_2$ just by looking at it. Most useful circuits are substantially more complex, but we'll start here to develop the concepts, and then apply it to more complex circuits. 

Applying KCL to $V_1$, we can obtain the following equation:
$$ I_{V_1 \rightarrow V_+} + I_{V_1 \rightarrow V_2} = 0 $$

If we assume the "positive" direction is away $V_1$, one of these current values will be negative, so that the current flowing into $V_1$ will equal the current flowing out of $V_1$. 

Applying Ohm's Law, we can re-write the above equation as:
$$ \frac{V_+ - V_1}{200} + \frac{V_2 - V_1}{100} = 0 $$

Which we can simplify to:

$$ 3V_1 - 2V_2 = V_+$$

We can do the same thing with $V_2$:

$$I_{V_2 \rightarrow V_1} + I_{V_2 \rightarrow 0} = 0 $$

$$\frac{V_1 - V_2}{100} + \frac{0 - V_2}{200} = 0$$

$$3V_2 -2V_1 = 0$$

Now we have a system of equations that we can express in matrix form:

$$
\begin{bmatrix}
3 && -2 \\
-2 && 3
\end{bmatrix}
\begin{bmatrix}
V_1 \\
V_2 
\end{bmatrix}
=
\begin{bmatrix}
V_+\\
0
\end{bmatrix}
$$

Since we know the value of $V_+$ we can write this as an augmented matrix and plug it into the solver function we created on the previous assignment. 

In [82]:
## TO DO: Copy and paste your 'solve_system(matrix)' function from yesterday's assignment. 
def solve_system(matrix):
    """
    Solves a system of linear equations
    Parameters:
        matrix(N x N+1 numpy array): the augmented matrix to be solved
    Returns:
        (N x 1 numpy array): array of the solutions to the linear equations
    """
    N = len(matrix)
    matrix = matrix.astype("float64")
    
    # This is inefficient but I do not care! It works!
    # Need to do partial pivot a lot so that it doesn't divide by 0, unsure how else to fix.

    # Partial pivot
    for i in range(N): 
        maxVal = matrix[i][i]
        maxRow = i
        for j in range(i+1, N):
            if (matrix[j][i] > maxVal):
                maxVal = matrix[j][i]
                maxRow = j

        matrix[[i, maxRow]] = matrix[[maxRow, i]]

    # Divide by diagonal terms
    for i in range(N): 
        if (matrix[i][i] != 0):
            matrix[i] = matrix[i] / matrix[i][i]

    # Partial pivot
    for i in range(N): 
        maxVal = matrix[i][i]
        maxRow = i
        for j in range(i+1, N):
            if (matrix[j][i] > maxVal):
                maxVal = matrix[j][i]
                maxRow = j

        matrix[[i, maxRow]] = matrix[[maxRow, i]]

    # Divide by diagonal terms
    for i in range(N): 
        if (matrix[i][i] != 0):
            matrix[i] = matrix[i] / matrix[i][i]

    # Make matrix upper-triangle
    for i in range(1, N):
        for j in range (0, i):
            term = matrix[i][j]
            matrix[i] = matrix[i] - term*matrix[j]

        if (matrix[i][i] != 0):
            matrix[i] = matrix[i] / matrix[i][i]

    # Partial pivot
    for i in range(N): 
        maxVal = matrix[i][i]
        maxRow = i
        for j in range(i+1, N):
            if (matrix[j][i] > maxVal):
                maxVal = matrix[j][i]
                maxRow = j

        matrix[[i, maxRow]] = matrix[[maxRow, i]]

    # Divide by diagonal terms
    for i in range(N): 
        if (matrix[i][i] != 0):
            matrix[i] = matrix[i] / matrix[i][i]

    # Perform backsubstitution
    for l in range(N-1, 0, -1):
        for k in range(l):
            matrix[k]-= matrix[k][l]*matrix[l]
    
    np.round(matrix)
    print(matrix)

    return matrix[:, -1]

In [83]:
## TO DO: Create the augemented matrix for the matrix equation shown above
test_a = np.array([[3, -2, 5], [-2, 3, 0]])

In [84]:
## TO DO: Solve the matrix using your solve_system function
print(solve_system(test_a))

[[1. 0. 3.]
 [0. 1. 2.]]
[3. 2.]


Applying the same process as above, find the voltages at  $V_1$, $V_2$, $V_3$, and $V_4$.

If you want to check your answer, you can solve it by hand, or build the circuit in https://www.falstad.com/circuit/

<img width=300px src = "Circuit1.png">

In [85]:
## TO DO: Create an augmented matrix for the above circuit
test_b = np.array([[-3, 1, 1, 0, -5], [1, -4, 1, 1, -5], [1, 1, -4, 1, 0], [0, 1, 1, -3, 0]])

In [86]:
## TO DO: Solve the matrix using your solve_system function
print(solve_system(test_b))

[[ 1.          0.          0.          0.          3.33333333]
 [ 0.          1.          0.          0.          3.        ]
 [ 0.          0.          1.          0.          2.        ]
 [-0.         -0.         -0.          1.          1.66666667]]
[3.33333333 3.         2.         1.66666667]


Applying the same process as above, find the voltages at  $V_1$, $V_2$, $V_3$, $V_4$, $V_5$, $V_6$, and $V_7$.

If you want to check your answer, you can solve it by hand, or build the circuit in https://www.falstad.com/circuit/

<img src = "Circuit2.png">

In [87]:
## TO DO: Create an augmented matrix for the above circuit
test_c = np.array([
[-2, 0, 1, 0, 0, 0, 0, -5], 
[0, -3, 0, 1, 1, 0, 0, -5], 
[1, 0, -4, 1, 0, 1, 0, -5], 
[0, 1, 1, -6, 1, 1, 0, -5], 
[0, 1, 0, 1, -4, 0, 1, 0], 
[0, 0, 1, 1, 0, -3, 0, 0], 
[0, 0, 0, 0, 1, 0, -2, 0]
,])

In [88]:
## TO DO: Solve the matrix using your solve_system function
print(solve_system(test_c))

[[ 1.          0.          0.          0.          0.          0.
   0.          4.21052632]
 [ 0.          1.          0.          0.          0.          0.
   0.          3.02631579]
 [ 0.          0.          1.          0.          0.          0.
   0.          3.42105263]
 [ 0.          0.          0.          1.          0.          0.
   0.          2.5       ]
 [ 0.          0.          0.          0.          1.          0.
   0.          1.57894737]
 [ 0.          0.          0.          0.          0.          1.
   0.          1.97368421]
 [-0.         -0.         -0.         -0.         -0.         -0.
   1.          0.78947368]]
[4.21052632 3.02631579 3.42105263 2.5        1.57894737 1.97368421
 0.78947368]
